### ISSUE TITLE
link to help page

### ISSUE THREAD

**Issue by dadorner** [fact-project/shifthelper_webinterface#20]
I guess there is somewhere some help text for this website (eg I was wondering what the 'I am awake' button is for and what consequences it has when I press it) - would be great to link it from the website

**Comment by dneise** [comment]
I'm not sure there is a documentation for the website itself, currently there is only the nascent [nightshift guide](https://github.com/fact-project/nightshift_guide)

The question you have about that button is for example explained here. 
https://github.com/fact-project/nightshift_guide#shutdown

We could set up a dedicated documentation page for that web page. It wouldn't hurt I guess, and doesn't cost much time. I will set one up and put a link on the shifthelper webinterface.

**Comment by maxnoe** [comment]
done
