### ISSUE TITLE
Log for users

### ISSUE THREAD

**Issue by dneise** [fact-project/shifthelper_webinterface#23]
Adrian @abiland and me recently discussed that it is needed for users to see what the shifthelper is doing at the moment. For example whom it is calling at the moment. 
I think this is connected to a request by @dadorner  as well.

At first there was the wish expressed to have this on the shifthelper website itself, but we found it might be easier to have this in a log file and present this logfile **somehow** on the shifthelper website (or a site linked from the shifthelper website). 

We used log.io for presenting logfiles on a website once, but it had no way to show the last 100 lines of a file, but only show new entries since loading time of the page, so a user who wants to see, if the shifthelper is currently calling the fallback or the flare expert, there is no chance .. one has to wait *minutes* until the next call goes out, so log.io is not suitable.

However, the general approach to create a logstream much smaller than the current logstream, e.g. only logging which calls go out, is imho very very easy. 
Also adding log entries to this stream in case certain users say: Well, I would also like to see if this or that check fires ... (not sure why, but let's say they want it)  is much easier than putting more stuff onto the website, I think. So providing such a log-stream is imho the way to go.

How to present this stream on a website ... well ... I'm not sure. 

I think currently the webinterface container has no access to the log file folder of the shifthelper, correct? 

I think as a start I would create a simple page which prints the entire (dayly!) logfile and that's it.
Just like the showlog pages, also this page would need to be refreshed manually. 

@MaxNoe would you deal with the part of giving the webinterface container access to the shifthelper logfiles? then I would create such a simple page.

**Comment by maxnoe** [comment]
Giving access to the logs should be as simple as mounting the directory which contains the file, this is docker option `-v <path on host>:<path in container>` or a `volumes` entry in the docker compose file.

I can do that.

**Comment by maxnoe** [comment]
Here is a stackoverflow answer on how to stream a log file: http://stackoverflow.com/questions/35540885/display-the-contents-of-a-log-file-as-it-is-updated

**Comment by dneise** [comment]
Awesome thanks for both comments

**Comment by kbruegge** [comment]
Not sure if this is really applicable here but anyways. There have been some examples of security breaches due to public log files. So one has to be careful about what to put in there and who can read it.
But you probably already know all that. So I'll stop rambling ;)

**Comment by dneise** [comment]
I don't know this ... please elaborate, or give us a link so we can read it up ...

**Comment by maxnoe** [comment]
I think this was mainly logs of the web servers or applications exposed. Which revealed something like precise version with known vulnerabilities or even passwords.

Like heartbleed: https://xkcd.com/1354/

**Comment by maxnoe** [comment]
Oh and also: we will only show this to logged in users i guess

**Comment by dneise** [comment]
right @ logged in only

**Comment by kbruegge** [comment]
> I think this was mainly logs of the web servers or applications exposed. Which revealed something like precise version with known vulnerabilities or even passwords.

Yes [this](https://cwe.mitre.org/data/definitions/533.html) kind of stuff. As I said. It might not apply here. Also were not really a high-risk target I'd say. But still. 
Heres are some random links a google search turned up.

- http://security.stackexchange.com/questions/81249/invalid-passwords-leaked-to-logfiles
- https://github.com/IdentityServer/IdentityServer3/issues/2321

Also log injection can be funny. Heres an interesting example:

- https://www.owasp.org/index.php/Log_Injection
