### ISSUE TITLE
Page broken for Safari

### ISSUE THREAD

**Issue by dneise** [fact-project/shifthelper_webinterface#28]
One cannot see the alert using the Safari browser. I think this was first reported by Sabrina and should be reproduced again by somebody of us... I think

**Comment by kbruegge** [comment]
This is what it looks like in safari.


![screen shot 2017-07-18 at 09 19 28](https://user-images.githubusercontent.com/4076745/28309582-163f1c4e-6baa-11e7-93e6-653632304112.png)

**Comment by dneise** [comment]
looks okay to me. Can we close this issue?
