### ISSUE TITLE
Link to Nightshift manual 

### ISSUE THREAD

**Issue by dneise** [fact-project/shifthelper_webinterface#32]
There should be a link to the "nightshift" manual, on the SH page. 

I have in the moment two manuals in mind:
 - **with** phone numbers, needs to be password protected
 - the same, just **without** the phone numbers, so people can read the "help" without the need to log in.

makes sense?

**Comment by dneise** [comment]
I'd like a very short version, explaining the *what* and *how* .. and a longer version explaining the *why* and more detailed *how*. 

I strongly feel that any "longish" docu that tries to explain how and why something in FACT is the case, must at some point fail. There is always a point where a written text, trying to somehow summarize code, will simply fail in explaining the stuff the readers is currently thinking about, so the reader will anyway go and read the code.... therefore I find it hard to start writing any longish docu, since I think ... whatever I explain is not what the reader wants to know, and whatever I do leave out, is exactly what a reader might wanna know.

**Comment by maxnoe** [comment]
done
