### ISSUE TITLE
complete date and time zone in Alert date

### ISSUE THREAD

**Issue by dneise** [fact-project/shifthelper_webinterface#33]
Having a complete date for each alert is great, but new shifters might be puzzled, whether it is UTC or La Palma time or their local time of their browser.

Let's be explicit and say what it is. Yes one can find it out, but it takes in the order of seconds to find it out, while reading and discarding the (potentially) superfluous letter "Z" takes our highly trained brains a split second or less.

I propose to stick to [https://en.wikipedia.org/wiki/ISO_8601] and just attach the Z to the time and be done with with it.

**Comment by maxnoe** [comment]
I was just about to open an Issue asking whether we need the timestamps at all on the main page.

**Comment by dneise** [comment]
See also #21

**Comment by maxnoe** [comment]
It's all utc now that #43 is merged
