### ISSUE TITLE
individual alert lists for WARNING and ERROR

### ISSUE THREAD

**Issue by dneise** [fact-project/shifthelper_webinterface#34]
we are currently planning to give shifters and experts their own lists of Alerts.

This boils down to giving the different alert levels their own list, I think.

**Comment by maxnoe** [comment]
I do not get the connection.

Experts vs. Shifters is done by the category not the level

**Comment by dneise** [comment]
Ah yeah, my mistake ... I constantly confuse level and category.

**Comment by dneise** [comment]
Erm ... wait I was to fast:
ERROR is a level right? As is WARNING, right? 

ERRORs go to the dev, while warnings go to the shifter, right?

**Comment by maxnoe** [comment]
No. The level has nothing to do with who gets the message.

This is decided by the category, currently we have three categories

* shifter
* developer
* check_error

The `check_error` category is built into pycustos and is used to report if checks raise an exception.

Currently we use two levels:
* WARNING for new messages
* INFO for already acknowledged kinds of alerts

INFO only generates a telegram message while WARNING results in calls, website updates and telegram messages

**Comment by dneise** [comment]
We also use ERROR

**Comment by maxnoe** [comment]
Not explicitly, exceptions result in alerts with category check_error and level ERROR. There is no FACTIntervalCheck creating ERROR messages

**Comment by maxnoe** [comment]
We have no the possiblity to select Shifter / Expert /All in the alert table. Closing.
